name: Android Unit Tests

on:
  workflow_dispatch: {}
  pull_request:
  push:
    branches: [main]
    paths:
      - mobile/**

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 100
    env:
      ORG_GRADLE_PROJECT_reactNativeArchitectures: x86_64
      GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1024m
    steps:
      - name: ⬢ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 👀 Check out repository
        uses: actions/checkout@v3
      - name: 🔨 Use JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: restore modules
        uses: actions/cache@master
        with:
          path: mobile/node_modules
          key: ${{ runner.os }}-${{ hashFiles('mobile/yarn.lock') }}
      - name: Install Dependencies
        run: cd mobile && yarn install --freeze.lock
      - name: Build Android
        run: cd mobile && yarn build
